package io.github.vevoly.jmulticache.api;

/**
 * 多级缓存配置名称的契约接口。
 * <p>
 * 所有由代码生成器自动生成的缓存名称枚举都应实现此接口。
 * 这为框架提供了一个统一的、类型安全的编程契约，保证所有配置枚举都提供 {@link #name()} 和 {@link #getNamespace()} 这两个核心方法。
 * 它还提供了一个便利的默认方法 {@link #buildKey(String...)} 来快速构建 Redis Key。
 * <p>
 * The contract interface for multi-level cache configuration names.
 * All cache name enums auto-generated by the code generator should implement this interface.
 * This provides the framework with a unified, type-safe programming contract, ensuring that all configuration enums provide the two core methods: {@link #name()} and {@link #getNamespace()}.
 * It also provides a convenient default method, {@link #buildKey(String...)}, for quickly constructing Redis keys.
 *
 * @author vevoly
 */
public interface JMultiCacheConfigName {

    /**
     * 返回枚举成员的名称，该名称应与 YML 配置文件中的配置 Key 完全匹配。
     * <p>
     * Returns the name of the enum constant, which must exactly match the configuration key in the YML file.
     *
     * @return 配置名称 / The configuration name.
     */
    String name();

    /**
     * 返回该缓存配置在 Redis 中使用的物理命名空间 (Key 前缀)。
     * <p>
     * Returns the physical namespace (key prefix) used by this cache configuration in Redis.
     *
     * @return 命名空间字符串 / The namespace string.
     */
    String getNamespace();

    /**
     * 提供一个默认的、用于构建简单 Key 的辅助方法。
     * <p>
     * Provides a default helper method for building simple keys.
     *
     * @param keyParts 要拼接到 namespace 后面的 key 的一个或多个组成部分。/ One or more parts to be appended to the namespace to form the key.
     * @return 完整的 Redis Key (例如: "namespace:part1:part2") / The full Redis key (e.g., "namespace:part1:part2").
     */
    default String buildKey(String... keyParts) {
        if (keyParts == null || keyParts.length == 0) {
            return getNamespace();
        }
        // 使用 StringBuilder 以获得更好的性能 / Use StringBuilder for better performance
        StringBuilder sb = new StringBuilder(getNamespace());
        for (String part : keyParts) {
            sb.append(":").append(part);
        }
        return sb.toString();
    }
}
